apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: go-app
  labels:
    app: postgres
type: Opaque  # Add this line explicitly
data:
  POSTGRES_DB: YXlpZ3lhZGI=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MDU0OW1hcnRpbg==
  JWT_SECRET_KEY: TXkgU2VjcmV0IEtleQ==
immutable: true