apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: go-app
  labels:
    app: backend-svc
spec:
  selector:
    app: backend
  ports:
  - port: 8082
    targetPort: 8082

    
