apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: go-app
spec:
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgis/postgis
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret-credentials
              key: POSTGRES_PASSWORD
        # Add PostgreSQL configuration parameters
        - name: POSTGRES_SHARED_BUFFERS
          value: "64MB"
        - name: POSTGRES_MAINTENANCE_WORK_MEM
          value: "64MB"
        - name: POSTGRES_WORK_MEM
          value: "16MB"
        - name: POSTGRES_EFFECTIVE_CACHE_SIZE
          value: "128MB"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres # Add this line
        - name: secrets-volume
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: secrets-volume
        secret:
          secretName: db-secret-credentials