apiVersion: v1
kind: Secret
metadata:
  name: db-secret-credentials
  namespace: go-app
  labels:
    app: postgres
type: Opaque  # Add this line explicitly
data:
  POSTGRES_DB: YXlpZ3lhZGI=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MDU0OW1hcnRpbg==
immutable: true