apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: go-app
  labels:
    app: postgres-svc
spec:
  selector:
    app: postgresdb
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP  # Adding explicit type for clarity